name: Build sysroot
on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux RISCV
            base: linux-debian
            arch: riscv64
            includes: ""
            tripple: riscv64-linux-gnu

          - name: Linux LoongArch64
            base: linux-debian
            arch: loong64
            includes: sysroot/lib64
            tripple: loongarch64-linux-gnu

          - name: Linux PowerPC64
            base: linux-debian
            arch: ppc64el
            includes: sysroot/lib64
            tripple: ppc64le-linux-gnu
            debextra: libc6-dev-ppc64

          - name: Linux S390X
            base: linux-debian
            arch: s390x
            includes: ""
            tripple: systemz-linux-gnu

    name: Build ${{ matrix.name }} sysroot
    runs-on: ubuntu-latest
    steps:
      - name: Update system packages
        run: sudo apt update

      - name: Install Debootstrap
        if: matrix.base == 'linux-debian'
        run: sudo apt install debootstrap

      - name: Build Debian root
        if: matrix.base == 'linux-debian'
        run: |
          sudo apt install qemu-user-static
          mkdir sysroot
          sudo debootstrap --arch=${{ matrix.arch }} --foreign unstable sysroot https://deb.debian.org/debian
          sudo chroot sysroot /debootstrap/debootstrap --second-stage
          sudo chroot sysroot apt update
          sudo chroot sysroot apt install -y gcc libc6-dev libstdc++-15-dev libgcc-s1 libx11-dev libwayland-dev libjack-dev libpulse-dev libsndio-dev libthai-dev libdrm-dev libgbm-dev ${{ matrix.debextra }}

      - name: Pack sysroot
        run: |
          sudo tar -cf sysroot.tar sysroot/usr sysroot/bin sysroot/lib sysroot/sbin ${{ matrix.includes }}

      - name: Upload sysroot
        uses: actions/upload-artifact@v4
        with:
          name: sysroot-${{ matrix.base }}-${{ matrix.arch }}
          path: sysroot.tar

      - name: Pack toolchain
        run: |
          rm sysroot.tar
          git clone https://github.com/OpenMinecraft-Dev/cross-toolchain-sysroot
          mkdir bin
          cp cross-toolchain-sysroot/llvm-shell/* ./bin
          rm -rf cross-toolchain-sysroot
          echo ${{ matrix.tripple }} > ./bin/target-tripple

          sudo tar -cf toolchain.tar bin sysroot/usr sysroot/bin sysroot/lib sysroot/sbin ${{ matrix.includes }}

      - name: Upload toolchain
        uses: actions/upload-artifact@v4
        with:
          name: llvm-toolchain-${{ matrix.base }}-${{ matrix.arch }}
          path: toolchain.tar

      - name: Test toolchain
        run: |
          echo "#include <stdio.h>" >> main.c
          echo "int main() {printf(\"Hello, world\");}" >> main.c
          ./bin/clang main.c -o main-c
          file main-c